spring.application.name=user
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:ecom
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create
below command is to enable H2 console when app is running from docker
Sspring.h2.console.settings.web-allow-others=true
