server.port=8083
spring.rabitmq.host=localhost
spring.rabitmq.port=5672
spring.rabitmq.username=guest
spring.rabitmq.password=guest

# Rabbit MQ related configuration
rabbitmq.exchange.name=order.exchange
rabbitmq.queue.name=order.queue
rabbitmq.routing.key=order.tracking

management.endpoints.web.exposure.include=*

# postgress
spring.datasource.url=jdbc:postgresql://localhost:5432/order?options=-c%20TimeZone=Asia/Kolkata
spring.datasource.username=embarkx
spring.datasource.password=embarkx

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
app.message=Hello order

eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

logging.level.root=INFO
logging.file.name = logs/${spring.application.name}.log
logging.file.logback.rollingpolicy.max-file-size=5MB 
logging.file.logback.rollingpolicy.max-history=7


management.tracing.sampling.probability = 1.0
management.endpoint.health.show-details=always
management.health.circuitbreakers.enabled=true

# Circuit Breaker
resilience4j.circuitbreaker.instances.productService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.productService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.productService.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.productService.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.productService.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.productService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.productService.automaticTransitionFromOpenToHalfOpenEnabled=true
resilience4j.circuitbreaker.instances.productService.slidingWindowType=count_based

# Retry
resilience4j.retry.instances.retryBreaker.maxAttempts=5
resilience4j.retry.instances.retryBreaker.waitDuration=5s

# Rate Limiter
resilience4j.ratelimiter.instances.rateBreaker.timeout-duration=0
resilience4j.ratelimiter.instances.rateBreaker.limit-refresh-period=4s
resilience4j.ratelimiter.instances.rateBreaker.limit-for-period=2