server.port=8081
spring.rabitmq.host=localhost
spring.rabitmq.port=5672
spring.rabitmq.username=guest
spring.rabitmq.password=guest
management.endpoints.web.exposure.include = *

#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:ecom
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=create
#below command is to enable H2 console when app is running from docker
#spring.h2.console.settings.web-allow-others=true

# postgress
#spring.datasource.url=jdbc:postgresql://localhost:5432/userdb?options=-c%20TimeZone=Asia/Kolkata
#spring.datasource.username=embarkx
#spring.datasource.password=embarkx
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# mongo DB
spring.data.mongodb.uri=mongodb://localhost:27017/userdb
spring.data.mongodb.database=userdb

eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

logging.level.root=INFO
logging.level.com.ecom.user=TRACE
logging.file.name = logs/${spring.application.name}.log
logging.file.logback.rollingpolicy.max-file-size=5MB 
logging.file.logback.rollingpolicy.max-history=7

management.tracing.sampling.probability = 1.0