spring.application.name=notification
server.port=8084
spring.rabitmq.host=localhost
spring.rabitmq.port=5672
spring.rabitmq.username=guest
spring.rabitmq.password=guest

# Rabbit MQ related configuration
rabbitmq.exchange.name=order.exchange
rabbitmq.queue.name=order.queue
rabbitmq.routing.key=order.tracking


