spring.application.name: ecomConfigServer
server.port=8888
spring.profiles.active=native
spring.cloud.config.server.native.search-locations=file:///D:/Education/10_JavaZone/SpringProjects/EmbarkX/Spring Boot Microservices Professional/ecom_microservice/ecomConfigServer/src/main/resources/configs/
spring.rabitmq.host=localhost
spring.rabitmq.port=5672
spring.rabitmq.username=guest
spring.rabitmq.password=guest
management.endpoints.web.exposure.include=*
# http://localhost:8888/user/default
#http://localhost:8888/product/default
#http://localhost:8888/order/default