spring.application.name: ecomConfigServer
server.port=8888
spring.profiles.active=native
spring.cloud.config.server.native.search-locations=file:///D:/Education/10_JavaZone/SpringProjects/EmbarkX/Spring Boot Microservices Professional/ecom_microservice/ecomConfigServer/src/main/resources/configs/

# http://localhost:8888/user/default
#http://localhost:8888/product/default
#http://localhost:8888/order/default