spring:
  application:
    name: springextconfig_p1
  config:
    import: "optional:configserver:http://localhost:8888/"
  profiles:
    active: dev
server:
  port: 8081

build:
  version: 123
  buidNum: 101
  packagedetails: jar

framworkdetails:
  java_version: 21
  springbootversion: 3.1.5
